# sudo: required
language: bash
services: docker

env:
  global:
    - REGISTRY_USER=storagebofh
    - secure: "jcXxdOykf/XLI/ImRv5sXHcxxC+EeaGBrUe1+3oLxGwvpcPgXZKrWKpzPV3BJE+9dc3zg4rF9qXDgjkCFV7ot5wxG6akeHL5Vc7M3xp6Zr3d4eW58IDOE6tERzggxqlxxD2oH56Px9gujmqkTV4V71KWGO0PjHQo3vz8KppWCViSucxakcrVZQv37paHdxczn35c1CqNxihYbVsSOr3BZhZaItaalzPHoB7EptGAcmILv8ioygrsrbPZ5JCEhcq7dV1M8f7fxQZbLa0iPXzfRh5Z3tC2WFRoU0JczcbV+pYE9dU5iBXI9mgvtYYei9NF/biYX5J89JScKL99eKneCxth+SLm94Wq5D9hxpMAZe+7UyqSuH/uxVtf+8XSdHNyG75LUkfJFLxdk6QIgpGggfoDMUTfp7/90X1NGbwSf1m++YrZH/HbYRumzsG9G/o4nukaSsfkM1+boJtMHrikk0ZU06KL5t0W35qviGCJRHV0fxJnJ56WQeDXh1pK9ceIWFCB2uAglda2RHBC/EgnsOn8dSJ2sBmxzl3RVU29vBdUFfXR/22UJa+WF5aU4LiXYVffh+VdQBLOmAG+hJSU9mrouzv0/5Ha5YVE+RJ4suq3riSPPZ3bbeJI28Niln598NOQP6hBfyCwh/0EoBo1nmZwG6spXrV62Q0v5wnkxuw="
  matrix:
    - COMPILER=gcc VERSION=4.8
    # - COMPILER=gcc VERSION=4.9
    # - COMPILER=gcc VERSION=5.4
    # - COMPILER=gcc VERSION=6.5
    # - COMPILER=gcc VERSION=7.4
    # - COMPILER=gcc VERSION=8.1
    # - COMPILER=gcc VERSION=9.1
    # - COMPILER=gcc VERSION=latest
    # - COMPILER=clang VERSION=3.6
    # - COMPILER=clang VERSION=3.7
    # - COMPILER=clang VERSION=3.8
    # - COMPILER=clang VERSION=3.9
    # - COMPILER=clang VERSION=4.0
    # - COMPILER=clang VERSION=5.0
    # - COMPILER=clang VERSION=6.0
    # - COMPILER=clang VERSION=7.1
    # - COMPILER=clang VERSION=8.0
    # - COMPILER=clang VERSION=9.0
    # - COMPILER=clang VERSION=latest

before_script:
  - env | sort
  - cd "$COMPILER"/"$VERSION"
  - image="$COMPILER:$VERSION"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
      docker run -ti --rm "$image" "$COMPILER" --version
    )

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: 
    - docker images

