# sudo: required
language: bash
services: docker

env:
  - COMPILER=gcc VERSION=4.8
  - COMPILER=gcc VERSION=4.9
  - COMPILER=gcc VERSION=5.4
  - COMPILER=gcc VERSION=6.5
  - COMPILER=gcc VERSION=7.4
  - COMPILER=gcc VERSION=8.1
  - COMPILER=gcc VERSION=9.1
  - COMPILER=gcc VERSION=latest
  - COMPILER=clang VERSION=3.6
  - COMPILER=clang VERSION=3.7
  - COMPILER=clang VERSION=3.8
  - COMPILER=clang VERSION=3.9
  - COMPILER=clang VERSION=4.0
  - COMPILER=clang VERSION=5.0
  - COMPILER=clang VERSION=6.0
  - COMPILER=clang VERSION=7.1
  - COMPILER=clang VERSION=8.0
  - COMPILER=clang VERSION=9.0
  - COMPILER=clang VERSION=latest

before_script:
  - env | sort
  - cd "$COMPILER"/"$VERSION"
  - image="$COMPILER:$VERSION"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
      docker run -ti --rm "$image" "$COMPILER" --version
    )

after_script:
  - docker images
